- name: Install MariaDB packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - mariadb-server
    - mariadb-connector-odbc
    - bash-completion
    - python3-PyMySQL
  become: yes

- name: Create Prometheus user
  user:
    name: prometheus
    shell: /bin/false
    createhome: true

- name: Start and enable MariaDB service
  service:
    name: mariadb
    state: started
    enabled: yes
  become: yes

- name: Config file
  template:
    src: my.cnf.j2
    dest: .my.cnf

- name: Config sql 
  loop:
    - create
    - insert
    - query
  template:
    src: "{{ item }}.sql.j2"
    dest: "/tmp/{{ item }}.sql"

- name: Create database
  mysql_db:
    name: ecommerce
    state: present
  become: yes

- name: Create database user
  mysql_user:
    name: ecommerce
    password: admin
    priv: "ecommerce.*:ALL"
    state: present
  become: yes